# Generated by Django 4.2.7 on 2026-02-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_systemconfiguration_ai_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='beta_mode',
            field=models.BooleanField(default=True, help_text='When enabled, shows test login cards on the sign-in page.'),
        ),
    ]
