# Generated by Django 4.2.7 on 2026-02-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemconfiguration_beta_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='lead_magnet_button_text',
            field=models.CharField(blank=True, default='Send Me the Recording', max_length=100),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='lead_magnet_description',
            field=models.TextField(blank=True, default='Leave your details and receive a guided relaxation recording enhanced with binaural beats, designed for stress relief and better sleep.'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='lead_magnet_email_body',
            field=models.TextField(blank=True, default='Thank you for your interest in calming your nervous system.\nClick the button below to download your free resource.', help_text='Plain-text email body. The download link/button is appended automatically.'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='lead_magnet_email_subject',
            field=models.CharField(blank=True, default='Your free Nervous System Reset recording', max_length=300),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='lead_magnet_file',
            field=models.FileField(blank=True, help_text='File that subscribers will receive (audio, PDF, etc.).', null=True, upload_to='lead_magnet/'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='lead_magnet_title',
            field=models.CharField(blank=True, default='Free Nervous System Reset Audio', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='lead_magnet_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
